<template>
  <div class="policy">
    <h2><b>PRIVACY POLICY</b></h2>
    <p>Effective date: 2020-03-30</p>
    <p>1. <b>Introduction</b></p>
    <p>Welcome to <b> www.koronavirusbih.com</b>.</p>
    <p><b>www.koronavirusbih.com</b> (“us”, “we”, or “our”) operates <b>https://www.koronavirusbih.com/</b> (hereinafter referred to as <b>“Service”</b>).</p>
    <p>Our Privacy Policy governs your visit to <b>https://www.koronavirusbih.com/</b>, and explains how we collect, safeguard and disclose information that results from your use of our Service.</p>
    <p>We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
    <p>Our Terms and Conditions (<b>“Terms”</b>) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (<b>“agreement”</b>).</p>
    <p>2. <b>Definitions</b></p>
    <p><b>SERVICE</b> means the https://www.koronavirusbih.com/ website operated by www.koronavirusbih.com.</p>
    <p><b>PERSONAL DATA</b> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
    <p><b>USAGE DATA</b> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
    <p><b>COOKIES</b> are small files stored on your device (computer or mobile device).</p>
    <p><b>DATA CONTROLLER</b> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
    <p><b>DATA PROCESSORS (OR SERVICE PROVIDERS)</b> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p> <p><b>DATA SUBJECT</b> is any living individual who is the subject of Personal Data.</p>
    <p><b>THE USER</b> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>
    <p>3. <b>Information Collection and Use</b></p>
    <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
    <p>4. <b>Types of Data Collected</b></p>
    <p><b>Personal Data</b></p>
    <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (<b>“Personal Data”</b>). Personally identifiable information may include, but is not limited to:</p>
    <p>0.1. Email address</p>
    <p>0.2. First name and last name</p>
    <p>0.3. Phone number</p>
    <p>0.4. Address, Country, State, Province, ZIP/Postal code, City</p>
    <p>0.5. Cookies and Usage Data</p>
    <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.</p>
    <p><b>Usage Data</b></p>
    <p>We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (<b>“Usage Data”</b>).</p>
    <p>This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
    <p>When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.</p>
    <p><b>Location Data</b></p><p>We may use and store information about your location if you give us permission to do so (<b>“Location Data”</b>). We use this data to provide features of our Service, to improve and customize our Service.</p><p>You can enable or disable location services when you use our Service at any time by way of your device settings.</p>
    <p><b>Tracking Cookies Data</b></p>
    <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
    <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.</p>
    <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
    <p>Examples of Cookies we use:</p>
    <p>0.1. <b>Session Cookies:</b> We use Session Cookies to operate our Service.</p>
    <p>0.2. <b>Preference Cookies:</b> We use Preference Cookies to remember your preferences and various settings.</p>
    <p>0.3. <b>Security Cookies:</b> We use Security Cookies for security purposes.</p>
    <p>0.4. <b>Advertising Cookies:</b> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</p>
    <p><b>Other Data</b></p>
    <p>While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, non-disclosure agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.</p>
    <p>5. <b>Use of Data</b></p>
    <p>www.koronavirusbih.com uses the collected data for various purposes:</p>
    <p>0.1. to provide and maintain our Service;</p>
    <p>0.2. to notify you about changes to our Service;</p>
    <p>0.3. to allow you to participate in interactive features of our Service when you choose to do so;</p>
    <p>0.4. to provide customer support;</p>
    <p>0.5. to gather analysis or valuable information so that we can improve our Service;</p>
    <p>0.6. to monitor the usage of our Service;</p>
    <p>0.7. to detect, prevent and address technical issues;</p>
    <p>0.8. to fulfil any other purpose for which you provide it;</p>
    <p>0.9. to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</p>
    <p>0.10. to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</p>
    <p>0.11. to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</p>
    <p>0.12. in any other way we may describe when you provide the information;</p>
    <p>0.13. for any other purpose with your consent.</p>
    <p>6. <b>Retention of Data</b></p>
    <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
    <p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
    <p>7. <b>Transfer of Data</b></p>
    <p>Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
    <p>If you are located outside Bosnia and Herzegovovina and choose to provide information to us, please note that we transfer the data, including Personal Data, to Bosnia and Herzegovovina and process it there.</p>
    <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
    <p>www.koronavirusbih.com will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
    <p>8. <b>Disclosure of Data</b></p>
    <p>We may disclose personal information that we collect, or you provide:</p>
    <p>0.1. <b>Disclosure for Law Enforcement.</b></p><p>Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</p><p>0.2. <b>Business Transaction.</b></p><p>If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</p><p>0.3. <b>Other cases. We may disclose your information also:</b></p><p>0.3.1. to our subsidiaries and affiliates;</p><p>0.3.2. to contractors, service providers, and other third parties we use to support our business;</p><p>0.3.3. to fulfill the purpose for which you provide it;</p><p>0.3.4. for the purpose of including your company’s logo on our website;</p><p>0.3.5. for any other purpose disclosed by us when you provide the information;</p><p>0.3.6. with your consent in any other cases;</p><p>0.3.7. if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.</p>
    <p>9. <b>Security of Data</b></p>
    <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
    <p>10. <b>Service Providers</b></p>
    <p>We may employ third party companies and individuals to facilitate our Service (<b>“Service Providers”</b>), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
    <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
    <p>11. <b>Analytics</b></p>
    <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
    <p>12. <b>CI/CD tools</b></p>
    <p>We may use third-party Service Providers to automate the development process of our Service.</p>
    <p>13. <b>Advertising</b></p><p>We may use third-party Service Providers to show advertisements to you to help support and maintain our Service.</p>
    <p>14. <b>Behavioral Remarketing</b></p>
    <p>We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.</p>
    <p>15. <b>Payments</b></p><p>We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p><p>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
    <p>16. <b>Links to Other Sites</b></p>
    <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
    <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
    <p>For example, the outlined Privacy Policy has been created using <a href="https://policymaker.io/">PolicyMaker.io</a>, a free web application for generating high-quality legal documents. PolicyMaker’s online privacy policy generator is an easy-to-use <a href="https://policymaker.io/privacy-policy/">free tool for creating privacy policy template</a> for a website, blog, online store or app.</p>
    <p>17. <b><b>Children’s Privacy</b></b></p>
    <p>Our Services are not intended for use by children under the age of 18 (<b>“Child”</b> or <b>“Children”</b>).</p>
    <p>We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.</p>
    <p>18. <b>Changes to This Privacy Policy</b></p>
    <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
    <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.</p>
    <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
    <p>19. <b>Contact Us</b></p>
    <p>If you have any questions about this Privacy Policy, please contact us by email: <b>dragutinavdalovic@gmail.com</b>.</p>
    <br/>
    <h2> <b> POLITIKA PRIVATNOSTI </b> </h2>
        <p> Datum stupanja na snagu: 2020-03-30 </p>
        <p> 1. <b>Uvod</b> </p>
        <p> Dobrodošli na <b> www.koronavirusbih.com </b>. </p>
        <p> <b> www.koronavirusbih.com </b> („mi“, „mi“ ili „naši“) djeluje kao<b> https://www.koronavirusbih.com/ </b> (u daljnjem tekstu: kao <b> "Usluga" </b>). </p>
        <p> Naša Pravila o privatnosti reguliraju vašu posjetu stranice<b> https://www.koronavirusbih.com/ </b> i objašnjavaju kako prikupljamo, čuvamo i otkrivamo informacije koje proizilaze iz vaše upotrebe naše Usluge. </p >
        <p> Vaše podatke koristimo za pružanje i poboljšanje usluge. Korištenjem usluge prihvaćate prikupljanje i korištenje informacija u skladu s ovim pravilima. Ako nije drugačije definisano u ovim Pravilima o privatnosti, izrazi korišteni u ovim Pravilima o privatnosti imaju isto značenje kao i u našim Uvjetima i odredbama. </p>
        <p> Naši Uslovi i odredbe (<b> „Uslovi“ </b>) regulišu svako korišćenje naše usluge i zajedno sa Politikom o privatnosti čini vaš ugovor sa nama (<b> „ugovor“ </b>). </p>
        <p> 2. <b> Definicije</b> </p>
        <p> <b> SERVIS </b> znači veb lokacija https://www.koronavirusbih.com/ kojom upravlja www.koronavirusbih.com. </p>
        <p> <b> LIČNI PODACI </b> znače podatke o živoj jedinki koji se mogu identifikovati iz tih podataka (ili iz onih i drugih podataka bilo u našem vlasništvu ili koji će vjerovatno doći u naše vlasništvo). </p>
        <p> <b> KORIŠTENI PODACI </b> su automatski prikupljeni podaci ili generisani korištenjem usluge ili iz same servisne infrastrukture (na primjer, trajanje posjete stranici). </p>
        <p> <b> COOKIES </b> su male datoteke spremljene na vašem uređaju (računar ili mobilni uređaj). </p>
        <p> <b> KONTROLA PODATAKA </b> znači fizička ili pravna osoba koja (samostalno ili zajednički ili zajednički s drugim osobama) određuje svrhe i način na koji se trebaju čuvati bilo koji lični podaci kao i obrađivati obrađen. U svrhu ovih Pravila o privatnosti, mi smo kontrolor podataka. </p>
        <p> <b> PROCESORI PODATAKA (ILI Pružatelji usluga) </b> znači bilo koja fizička ili pravna osoba koja obrađuje podatke u ime kontrolera podataka. Možemo koristiti usluge različitih davatelja usluga radi efikasnije obrade vaših podataka. </p> <p> <b> SUBJEKT PODATAKA </b> je bilo koja živa osoba koja je predmet Osobnih podataka. </p>
        <p> <b> KORISNIK </b> je pojedinac koji koristi našu uslugu. Korisnik odgovara Subjektu podataka koji je predmet Osobnih podataka. </p>
        <p> 3. <b> Prikupljanje i upotreba informacija </b> </p>
        <p> Prikupljamo nekoliko različitih vrsta informacija u različite svrhe kako bismo vam pružili i poboljšali našu uslugu. </p>
        <p> 4. <b> Vrste prikupljenih podataka </b> </p>
        <p> <b> Lični podaci </b> </p>
        <p> Dok koristite našu uslugu, možemo od vas tražiti da nam date određene lične informacije koje se mogu koristiti za kontakt ili identifikaciju (<b> „lični podaci“ </b>). Podaci koji se mogu tražiti mogu sadržavati, ali nisu ograničeni na: </p>
        <p> 0.1 Adresa e-pošte </p>
        <p> 0.2. Ime i prezime </p>
        <p> 0.3 Broj telefona </p>
        <p> 0.4. Adresa, država, država, pokrajina, poštanski broj, grad </p>
        <p> 0.5. Kolačići i podaci o upotrebi </p>
        <p> Možemo koristiti vaše lične podatke da vas kontaktiramo sa biltenima, marketinškim ili promotivnim materijalima i drugim informacijama koje bi vas mogle zanimati. Možete isključiti primanje bilo koje ili sve ove komunikacije od nas ako prijavite odjavu. </p>
        <p> <b> Podaci o upotrebi </b> </p>
        <p> Takođe možemo prikupiti podatke koje vaš pregledač šalje kad god posetite naš servis ili kada pristupite servisu putem ili preko bilo kojeg uređaja (<b> „Podaci o upotrebi“ </b>). </p>
        <p> Ovi podaci o upotrebi mogu sadržavati podatke poput adrese Internet protokola vašeg računara (npr. IP adresa), vrste preglednika, verzije preglednika, stranice naše Usluge koju posjetite, vremena i datuma vaše posjete, vremena provedenog na stranici, jedinstvene identifikatore uređaja i druge dijagnostičke podatke. </p>
        <p> Kada pristupite usluzi s uređajem, ovi podaci o upotrebi mogu sadržavati informacije poput vrste uređaja koji koristite, jedinstvenog ID-a uređaja, IP adrese vašeg uređaja, operativnog sistema vašeg uređaja, vrste internetskog pregledača koji koristite , jedinstvene identifikatore uređaja i druge dijagnostičke podatke. </p>
        <p> <b> Podaci o lokaciji </b> </p> <p> Možemo koristiti i pohraniti podatke o vašoj lokaciji ako nam date dozvolu za to (<b> „Podaci o lokaciji“ </b>). Te podatke koristimo za pružanje značajki naše usluge, za poboljšanje i prilagođavanje naše usluge. </p> <p> Lokacijske usluge možete omogućiti u bilo kojem trenutku kada koristite naš servis pomoću podešavanja vašeg uređaja. </p>
        <p> <b> Praćenje podataka o kolačićima </b> </p>
        <p> Koristimo kolačiće i slične tehnologije praćenja za praćenje aktivnosti na našem servisu i zadržavamo određene informacije. </p>
        <p> Kolačići su datoteke s malom količinom podataka koje mogu sadržavati jedinstveni anonimni identifikator. Kolačići se šalju vašem pretraživaču sa web stranice i pohranjuju se na vašem uređaju. Ostale tehnologije praćenja se takođe koriste poput svjetionika, oznaka i skripti za prikupljanje i praćenje informacija te za poboljšanje i analizu naše usluge. </p>
        <p> Možete omogućiti u pregledniku da odbije sve kolačiće ili da naznači kada se kolačić šalje. Međutim, ako ne prihvatate kolačiće, možda nećete moći koristiti neke dijelove naše Usluge. </p>
        <p> Primjeri kolačića koje koristimo: </p>
        <p> 0.1 <b> Session cookies (kolačići sesije): </b> Mi koristimo Session Cookies (kolačiće sesije) za rad naše usluge. </p>
        <p> 0.2. <b> Preference kolačići: </b> Koristimo preferencijalne kolačiće da bismo zapamtili vaše postavke i različita podešavanja. </p>
        <p> 0.3 <b> Sigurnosni kolačići: </b> Sigurnosne kolačiće koristimo u sigurnosne svrhe. </p>
        <p> 0.4. <b> Oglašivački kolačići: </b> Oglašavački kolačići koriste se za opsluživanje oglasa koji mogu biti relevantni za vas i vaše interese. </p>
        <p> <b> Ostali podaci </b> </p>
        <p> Tokom korištenja naše usluge možemo također prikupiti sljedeće podatke: spol, starost, datum rođenja, mjesto rođenja, podatke o pasošu, državljanstvo, registraciju u mjestu prebivališta i stvarnu adresu, telefonski broj (posao, mobilni), detalji dokumenata o obrazovanju, kvalifikaciji, stručnom usavršavanju, ugovori o zapošljavanju, ugovori o neotkrivanju podataka, informacije o bonusima i naknadama, podaci o bračnom statusu, članovima porodice, socijalnom osiguranju (ili drugoj identifikaciji poreznih obveznika), lokaciji ureda i drugim podacima. </p>
        <p> 5. <b> Upotreba podataka </b> </p>
        <p> www.koronavirusbih.com koristi prikupljene podatke u različite svrhe: </p>
        <p> 0.1 za pružanje i održavanje naše usluge; </p>
        <p> 0.2. da vas obavestimo o promenama naše usluge; </p>
        <p> 0.3 da vam omogući da učestvujete u interaktivnim funkcijama naše Usluge kada to odlučite; </p>
        <p> 0.4. pružiti korisničku podršku; </p>
        <p> 0.5. prikupiti analize ili vrijedne informacije kako bismo poboljšali našu uslugu; </p>
        <p> 0.6. za nadgledanje upotrebe naše usluge; </p>
        <p> 0.7. za otkrivanje, sprečavanje i rešavanje tehničkih problema; </p>
        <p> 0.8. ispuniti bilo koju drugu uslugu koju pružamo; </p>
        <p> 0.9. da izvršavamo svoje obaveze i provodimo svoja prava koja proizilaze iz bilo kojeg ugovora sklopljenog između vas i nas, uključujući naplatu i pretplatu; </p>
        <p> 0.10. da vam dostavimo obavijesti o vašem računu i / ili pretplati, uključujući obavijesti o isteku i obnavljanju, e-mail upute, itd .; </p>
        <p> 0,11 da vam pružimo vijesti, posebne ponude i opće informacije o ostalim proizvodima, uslugama i događajima ako nudimo slične onima koje ste već kupili ili se raspitivali, osim ako niste odlučili da takve podatke ne primite; </p>
        <p> 0,12. na bilo koji drugi način koji možemo opisati kada date informacije; </p>
        <p> 0,13 u bilo koje druge svrhe uz vaš pristanak. </p>
        <p> 6. <b> Zadržavanje podataka </b> </p>
        <p> Vaše lične podatke zadržaćemo samo onoliko dugo koliko je nužno za potrebe utvrđene u ovim Pravilima o privatnosti. Mi ćemo zadržati i koristiti vaše osobne podatke u mjeri koja je potrebna da bismo ispunili naše zakonske obveze (na primjer, ako smo dužni zadržati vaše podatke u skladu s važećim zakonima), riješiti sporove i provoditi naše pravne ugovore i politike. </p>
        <p> Takođe ćemo zadržati podatke o upotrebi za potrebe interne analize. Podaci o upotrebi uglavnom se čuvaju kraće, osim kada se ti podaci koriste za jačanje sigurnosti ili za poboljšanje funkcionalnosti naše Usluge ili smo zakonski obvezni da te podatke čuvamo u dužem vremenskom periodu. </p>
        <p> 7. <b> Prenos podataka </b> </p>
        <p> Vaši podaci, uključujući lične podatke, mogu se prenijeti na i održavati na računarima koji se nalaze izvan vaše države, provincije, države ili druge državne nadležnosti, gdje se zakoni o zaštiti podataka mogu razlikovati od onih iz vaše nadležnosti. </p>
        <p> Ako se nalazite izvan Bosne i Hercegovine i odlučite da nam date informacije, imajte na umu da podatke, uključujući lične podatke, prenosimo u Bosnu i Hercegovinu i obrađujemo tamo. </p>
        <p> Vaša saglasnost na ovu Politiku privatnosti praćena slanjem takvih podataka predstavlja vaš pristanak na taj prenos. </p>
        <p> www.koronavirusbih.com će poduzeti sve potrebne korake kako bi osigurao da se vaši podaci tretiraju na siguran način i u skladu s ovim Pravilima o privatnosti, a nikakav prenos vaših osobnih podataka neće se dogoditi organizaciji ili zemlji ukoliko nema odgovarajuće uspostavljene kontrole, uključujući sigurnost vaših podataka i drugih ličnih podataka. </p>
        <p> 8. <b> Otkrivanje podataka </b> </p>
        <p> Možemo otkriti lične podatke koje sakupljamo ili ih pružiti: </p>
        <p> 0.1 <b> Otkrivanje podataka za sprovođenje zakona. </b> </p> <p> Pod određenim okolnostima, od nas će se možda tražiti da obelodanimo vaše lične podatke ako je to potrebno zakonom ili kao odgovor na važeće zahteve javnih vlasti. </p> <p> 0.2. <b> Poslovna transakcija. </b> </p> <p> Ako smo mi ili naše podružnice uključene u spajanje, kupovinu ili prodaju imovine, vaš Personalni podaci mogu se prenijeti. </p> <p> 0.3. <b> Ostali slučajevi. Možemo takođe otkriti vaše podatke: </b> </p> <p> 0.3.1. našim podružnicama i povezanim društvima; </p> <p> 0.3.2. dobavljačima, pružaocima usluga i drugim trećim stranama koje koristimo za podršku našem poslu; </p> <p> 0.3.3. ispuniti svrhu za koju ih pružate; </p> <p> 0.3.4. u svrhu uključivanja logotipa vaše kompanije na našu web stranicu; </p> <p> 0.3.5. u bilo koju drugu svrhu koju nam otkrijete kada date informacije; </p> <p> 0.3.6. uz vaš pristanak u bilo kojem drugom slučaju; </p> <p> 0.3.7. ako smatramo da je otkrivanje potrebno ili prikladno za zaštitu prava, imovine ili sigurnosti Kompanije, naših kupaca ili drugih. </p>
        <p> 9. <b> Sigurnost podataka </b> </p>
        <p> Sigurnost vaših podataka za nas je važna, ali imajte na umu da nijedna metoda prijenosa putem Interneta ili način elektroničkog pohranjivanja nisu 100% sigurni. Iako se trudimo da koristimo komercijalno prihvatljiva sredstva za zaštitu vaših ličnih podataka, ne možemo garantovati njegovu apsolutnu sigurnost. </p>
        <p> 10. <b> Pružaoci usluga </b> </p>
        <p> Možemo zaposliti kompanije trećih lica i pojedince da bi olakšali našu uslugu (<b> „pružaoci usluga“ </b>), pružili uslugu u naše ime, vršili usluge povezane sa uslugom ili nam pomogli u analizi kako se naša usluga koristi . </p>
        <p> Ove treće strane imaju pristup vašim ličnim podacima samo da bi obavljale ove zadatke u naše ime i obavezne su da ih ne otkrivaju ili koriste u druge svrhe. </p>
        <p> 11 <b> Analitika</b> </p>
        <p> Možemo koristiti pružatelje usluga treće strane za nadgledanje i analizu upotrebe naše usluge. </p>
        <p> 12. <b> CI / CD alati </b> </p>
        <p> Možemo koristiti pružatelje usluga treće strane za automatizaciju procesa razvoja naše usluge. </p>
        <p> 13. <b> Oglašavanje</b></p> <p> Možemo koristiti pružatelje usluga trećih strana da vam prikazuju oglase kako bismo vam pomogli da podržite i održavate našu uslugu. </p>
        <p> 14. <b> Ponavljanje ponovnog marketinga </b> </p>
        <p> Možemo koristiti usluge remarketinga za oglašavanje na web lokacijama trećih strana nakon što ste posjetili naš servis. Mi i naši dobavljači trećih strana koristimo kolačiće za informiranje, optimizaciju i posluživanje oglasa na osnovu vaših prošlih posjeta našoj usluzi. </p>
        <p> 15. <b> Plaćanja</b></p> <p> U okviru Usluge možemo pružiti plaćene proizvode i / ili usluge. U tom slučaju koristimo usluge treće strane za obradu plaćanja (npr. Procesore plaćanja). </p> <p> Nećemo pohranjivati ​​niti prikupljati podatke o vašoj platnoj kartici. Te se informacije pružaju izravno našim trezorima plaćanja trećih strana čije korištenje vaših osobnih podataka uređuje njihova Politika privatnosti. Ovi procesori plaćanja pridržavaju se standarda koje postavlja PCI-DSS kao što vodi PCI Vijeće za sigurnosne standarde, što je zajednički napor marki poput Visa, Mastercard, American Express i Discover. PCI-DSS zahtjevi pomažu u osiguravanju sigurnog rukovanja podacima o plaćanju. </p>
        <p> 16. <b> Linkovi na druge web lokacije </b> </p>
        <p> Naša usluga može sadržavati veze do drugih web lokacija koje mi ne upravljamo. Ako kliknete vezu treće strane, bit ćete preusmjereni na web mjesto te treće strane. Toplo vam savjetujemo da pregledate Politiku privatnosti svake stranice koju posjetite. </p>
        <p> Mi nemamo kontrolu nad i ne preuzimamo odgovornost za sadržaj, politike privatnosti ili prakse bilo kojih trećih strana ili usluga. </p>
        <p> Na primjer, opisana Pravila o privatnosti kreirana su pomoću <a href="https://policymaker.io/"> PolicyMaker.io </a>, besplatne web aplikacije za generiranje visokokvalitetnih pravnih dokumenata. Online generator politika privatnosti PolicyMaker-a je <a href="https://policymaker.io/privacy-policy/"> besplatni alat za izradu predloška politike privatnosti </a> za web stranicu, blog, internetsku trgovinu ili aplikacije. </p>
        <p> 17. <b> <b> Privatnost dece </b> </b> </p>
        <p> Naše usluge nisu namenjene deci mlađoj od 18 godina (<b> „dete“ </b> ili <b> „deca“ </b>). </p>
        <p> Mi svesno ne prikupljamo lične podatke od dece mlađe od 18 godina. Ako postanete svesni da nam je dete dostavilo lične podatke, molimo kontaktirajte nas. Ako postanemo svjesni da smo od djece prikupljali lične podatke bez provjere roditeljskog pristanka, poduzimamo korake za uklanjanje tih podataka s naših servera. </p>
        <p> 18. <b> Izmene ove politike privatnosti </b> </p>
        <p> Možemo povremeno ažurirati našu Politiku privatnosti. Obavijestit ćemo vas o svim promjenama objavljivanjem novih Pravila o privatnosti na ovoj stranici. </p>
        <p> Obaveštavat ćemo vas putem e-maila i / ili istaknutog obaveštenja o našoj Usluzi, pre nego što promene postanu na snazi ​​i ažuriramo „efektivni datum“ na vrhu ove Politike privatnosti. </p>
        <p> Savetujemo vam da periodično pregledate ovu Politiku privatnosti radi bilo kakvih promena. Izmene ove Politike privatnosti na snazi ​​su kada su objavljene na ovoj stranici. </p>
        <p> 19 <b> Kontaktirajte nas </b> </p>
        <p> Ako imate bilo kakvih pitanja o ovim Pravilima o privatnosti, kontaktirajte nas putem e-maila: <b> dragutinavdalovic@gmail.com </b>. </p>
  </div>
</template>

<script>
  export default {
    name: 'PrivacyPolicy',
    layout: 'blog',
    props: {
      msg: String
    },
    components: {
    }
  }
</script>

<style scoped>
  .policy {
    width: 95%;
    margin: auto;
    text-align: justify;
    font-size: 16px;
    line-height: 1.2;
  }
  h2 {
    color: white;
  }
  p{
    color: white;
    line-height: 1.2;
    margin: 5px 0;
  }
  a {
    color: deepskyblue;
  }
</style>
